config/routes.rb
Rails.application.routes.draw do
  root "homepages#index"
  devise_for :users
  resources :games, only: [:index] do
    resources :game_posts, only: [:index, :destroy] 
  end
  
  get "/game_posts/:id", to: "homes#index"
  get "/games/new", to: "homes#index"
  get "/game_posts/new", to: "homes#index"
  
  namespace :api do
    namespace :v1 do
      resources :games, only: [:index, :create] 
      resources :searches, only: [:create]
      resources :game_posts, only: [:show, :new, :create] do
        resources :registrations, only: [:create]
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
    def index
    end
  end

app/views/homepages/index.html.erb
<div class="text-center">
    <img class="image-topper landing-image" src="https://cdn2.iconfinder.com/data/icons/xbox-one-controllers/500/gamer_Pink_Shadow-512.png" alt="Controller Picture" />
<div>
<div class="page-items center show-page sessions borders">
    <h3>Welcome to The Great Divide!</h3>
    <h4>My name is Josef! I appreciate you visiting my personal video game team building app. This means you can meet people here to play with them in your favorite game of choice! All systems and games are welcome here. If you don't see a game you like, go ahead and add it! Just sign up to begin meeting other gamers.<h4>
    <%= link_to "Get Started", games_path, class: "button new-success join-border" %>
</div>