config/routes.rb
Rails.application.routes.draw do
  root "homepages#index"
  devise_for :users
  resources :games, only: [:index] do
    resources :game_posts, only: [:index, :destroy] 
  end
  
  get "/game_posts/:id", to: "homes#index"
  get "/games/new", to: "homes#index"
  get "/game_posts/new", to: "homes#index"
  
  namespace :api do
    namespace :v1 do
      resources :games, only: [:index, :create] 
      resources :searches, only: [:create]
      resources :game_posts, only: [:show, :new, :create] do
        resources :registrations, only: [:create]
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :game_posts
    validates :title, presence: true, uniqueness: true

end

app/controllers/api/v1/games_controller.rb
require 'net/https'
class Api::V1::GamesController < ApplicationController
    protect_from_forgery unless: -> { request.format.json? }

    def index
        @all_games = Game.all
        render json: @all_games
    end

    def create
        @new_game = Game.new(title: params["name"])

        if @new_game.save
            render json: {}
        else 
            render json: {error: @new_game.errors.full_messages, status: :unprocessable_entity }
        end

    end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :authenticate_user!, except: [:index]

    def index
        @games = Game.all
    end

    def show
        @this_game = Game.find(params[:id])
    end

end

app/views/games/index.html.erb
<h1 class="center" >Available Games:</h1>
<div class="grid-container">
    <%@games.each do |game|%>
        <div class="callout cell page-items"> 
            <h2 class="center" ><%=link_to "#{game.title}", game_game_posts_path(game.id), class: "page-items"%></h2>

        </div>
    <%end%>
    <%= link_to "Add Game", "/games/new", class: "button new-success"%>
</div>

app/views/games/new.html.erb
<h1 class="center" >New Game</h1>


<%= form_for(@new_game) do |f|%>

<%=f.label :title, class: "form-labels sessions wisteria", value: "Game Title:"%>
<%=f.text_field :title, class: "form-labels text-field"%>

<%=f.submit "Add Game", class: "button new-success"%>
<%end%>